name: signal-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - ruptures
  - dcor
  - sktime
  - u8darts
  - ydata-profiling
  - setuptools<81 # required for ydata-profiling package
  - ipywidgets
